name: Tests and Linter

on:
  push:
    branches:
      - "main"
      - "release/*"
    paths:
      - '**.rs'
      - '**.py'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/pyproject.toml'
      - '**/poetry.lock'
  pull_request:
    branches:
      - "main"
      - "release/*"
    paths:
      - '**.rs'
      - '**.py'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/pyproject.toml'
      - '**/poetry.lock'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  backend-linter:
    name: "Backend (linter)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.2
        with:
          workspaces: "mosaicod -> target"
          cache-targets: true
          cache-on-failure: true

      - name: Run Linter
        working-directory: mosaicod
        run: cargo lint

  backend-unit-tests:
    name: "Backend (unit tests)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.2
        with:
          workspaces: "mosaicod -> target"
          cache-targets: true
          cache-on-failure: true

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Run Unit Tests
        run: ./scripts/tests.sh --mosaicod

  python-sdk-unit-tests:
    name: "Python SDK (unit tests)"
    runs-on: ubuntu-latest
    env:
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: '3.13'
          cache: 'poetry'

      - name: Run Unit Tests
        run: ./scripts/tests.sh --sdk-python

  integration-tests:
    name: "Integration tests"
    runs-on: ubuntu-latest
    needs: [backend-linter, backend-unit-tests, python-sdk-unit-tests]
    env:
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.2
        with:
          workspaces: "mosaicod -> target"
          cache-targets: true
          cache-on-failure: true

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: '3.13'
          cache: 'poetry'

      - name: Run Integration Tests
        run: ./scripts/tests.sh --integration
